---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Task
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  Callback::Frame: 0
  Guard: 0
  JSON::XS: 0
  Log::Defer: 0.201
  common::sense: 0
resources:
  bugtracker: https://github.com/hoytech/AnyEvent-Task/issues
  repository: git://github.com/hoytech/AnyEvent-Task.git
version: 0.720
