--- #YAML:1.0
name:               AnyEvent-Task
version:            0.800
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:         0
    Callback::Frame:  0
    common::sense:    0
    Guard:            0
    JSON::XS:         0
    Log::Defer:       0.300
resources:
    bugtracker:  https://github.com/hoytech/AnyEvent-Task/issues
    repository:  git://github.com/hoytech/AnyEvent-Task.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
